<h1>Change Password</h1><br/>

<form id="formEditUser" action="?controller=users&action=update" method="POST">
    <input type="hidden" name="id" value="<?php echo $User[ 'id' ] ?>">
    <input type="hidden" name="sub-action" value="edit-password">
    <div>
        <label for="password">Password</label><br/>
        <input type="password" name="users[password]" id="password">
    </div><br/>
    <div>
        <label for="re-password">Confirm Password</label><br/>
        <input type="password" name="re-password" id="re-password">
        <span class="tooltip-form" style="display:none;"></span>
    </div><br/>
    <div>
        <input type="submit" class="btn btn-success" value="Save new password">
        <a href="?controller=users&action=edit&id=<?php echo $User[ 'id' ] ?>" class="btn btn-inverse">Back</a>
    </div>
</form>