<h1>CRUD List Books</h1><br/>

<a href="?controller=books&action=create" class="btn btn-success">Create Book</a><br/><br/>

<table class="table table-condesed table-hover table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Author</th>
            <th>ISBN</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php 
            if ( !is_null( $Books ) ) {
                while ( $book = $Books->fetch_assoc() ) {
        ?>
        <tr>
            <td><?php echo $book[ 'id' ]; ?></td>
            <td><?php echo $book[ 'title' ]; ?></td>
            <td><?php echo $book[ 'author' ]; ?></td>
            <td><?php echo $book[ 'isbn' ]; ?></td>
            <td>
                <a href="?controller=books&action=show&id=<?php echo $book[ 'id' ] ?>" class="btn btn-info">Show</a>
                <a href="?controller=books&action=edit&id=<?php echo $book[ 'id' ] ?>" class="btn btn-warning">Edit</a>
                <a href="?controller=books&action=delete&id=<?php echo $book[ 'id' ] ?>" class="btn btn-danger">Destroy</button>
            </td>
        </tr>
        <?php
                }
            } else {
        ?>
        <tr>
            <td colspan="5" class="emptyUsers">No hay Libros registrados</td>
        </tr>
        <?php
            }
        ?>
    </tbody>
</table>